parquet-go/parquet-go

.github/workflows/test.yml
we already state go 1.20 in go.mod
=> only run tests on 1.20.x

CHANGELOG.md
move PR link after description
=> reformat changelog

README.md
I'm neither employed nor paid by twilio to maintain this.
If you are here, please see related #36
=> Update README to state its  community maintained

merge.go, merge_test.go, row_group_test.go
=> fix merging empty row groups

compare.go
This commit adds a pool to allocate column index slices during comparisons. Production profiles have shown these slices to account for 10% of our allocations in terms of space.
The pool is relatively simple. It returns nothing but a fixed-size slice regardless of the number of columns being processed to avoid pool fragmentation. The capacity of these slices have been bumped up to 128 from 64 given that it allows for a higher number of columns (beneficial to us specifically) with only a 512B increase per allocation which should be amortized by the pool now anyway.
=> Pool column index buffers when performing comparisons

merge.go, sorting_test.go
=> fix SortingWriter

.github/release.yml, .github/workflows/release.yml
This will help automate the release process, all we need to do is push a tag and the workflow takes care of the rest.
I created the related labels.
=> add release workflow

compress/zstd/zstd.go
This seems pretty straightforward, and I copied the style for defining a level. The only question I had was whether it was worth creating separate encoder and decoder concurrency levels, but that seemed unnecessary. If someone really needs it, they can always use two separate Codec objects.
Fixes #123
=> zstd: add concurrency option to codec

CONTRIBUTING.md
This reflects my understanding of the different stakeholders, and
tries to find a balance between that and ensuring forward progress is
possible. Please give me your thoughts.
=> CONTRIBUTING.md: try to codify merge policy

column.go, column_test.go
=> Fix columnPages SeekToRow

writer.go, writer_test.go
=> The minvalue of the column statistic incorrectly ignores empty string

writer.go
=> fix parquet specification version in file metadata

merge.go, merge_test.go, sorting_test.go
This adds a unit test that recreates the failure seen in #139 
The merged row reader will overwrite values in its internal buffers when filling up the buffer during the `ReadRows` call. 
This causes data corruption in the final `rows` that are returned to the caller.
This adds a potential fix for this issue by called the `rowAllocator` capture method we can copy in the byte arrays. However this creates some significant hits to the benchmarks seen below. Is there a better solution to prevent this buffer corruption? 
```bash
name                                                        old time/op    new time/op    delta
MergeRowGroups/BOOLEAN/groups=1,rows=10000-10                 20.7µs ± 0%    23.8µs ± 0%    +14.79%  (p=0.000 n=9+9)
MergeRowGroups/BOOLEAN/groups=2,rows=20000-10 …
```
=> Sorting merge data corruption

order_purego.go, order_test.go
Simple code maintenance to reduce the amount of code we have to maintain.
=> parquet: use generic implementation of ordering functions in purego build

.github/workflows/Dockerfile, .github/workflows/s390x-test.yaml, bloom.go, column_buffer.go, column_index_be.go, column_index_le.go, convert.go, dictionary.go, encoding/plain/plain.go, encoding/rle/rle.go, internal/bitpack/unpack_int32_purego.go, internal/bitpack/unpack_int64_purego.go
=> Enable parquet package support on s390x - rebased

README.md
=> chore(readme): Add badges and refactor readme header

config.go, file.go, file_test.go
=> add optimistic read file option

column_buffer.go, parquet_test.go
=> validate size of fixed-length values written

bloom/xxhash/sum64uint_amd64.s, internal/bytealg/count_amd64.s
=> fix: change r15 usage so its not clobbered with go plugin buildmode

reader.go, reader_test.go
This PR adds a GetKeyValueMetadata method to NewGenericReader and NewReader, to be able to read back the key value metadata set whilst writing the file.
=> reader: Add ability to read back Key Value metadata

page.go, row_group_test.go
This PR is a minor optimization to reuse pages that get discarded when seeking through async pages.
I added a benchmark that help me identify the issue.
=> release async pages when seeking

allocator.go, buffer.go, column_chunk.go, file.go, file_test.go, multi_row_group.go, reader.go, row.go, row_group.go
Building on the changes from #220, this PR improves the read mode APIs to make the asynchronous behavior a wrapper instead of passing it as argument in functions throughput the code.
=> improve async mode

file.go, file_test.go
There was a bug in the optimistic read logic that made it just not work, this PR addresses it and adds a test to make sure it remains working.
=> test opening files with optimistic read

CODEOWNERS
=> CODEOWNERS: update for 2025

page.go
As reported by @joe-elliott https://gophers.slack.com/archives/C04PVAL830Q/p1740077241635799 (thanks!), we introduced a performance regression in https://github.com/parquet-go/parquet-go/pull/229 where reading async columns would be started _too_ lazily, resulting in a serializing the initial page reads.
The intent was to not affect the historical behavior, and start reading _all_ columns asynchronously when either `ReadRows` or `SeekToRow` is called, but we were only doing so when calling `ReadRows`.
This PR fixes the intended behavior by starting the readers when `SeekToRow` is called, allowing [this code](https://github.com/parquet-go/parquet-go/blob/367c381/row_group.go#L295-L304) to kick off reading all columns concurrently.
Please take a look and let me know if you have any …
=> fix performance regression when reading rows from async pages

buffer.go, config.go, node.go, node_test.go, sorting.go, writer.go, writer_test.go
Fixes https://github.com/parquet-go/parquet-go/issues/258
=> Configuration for using another encoding as default

go.mod, go.sum, go.tools.mod, go.tools.sum, print.go
Fixes #286
Quality of life improvement: use Claude Code to generate replacements for open-source dependencies that introduced breaking changes.
=> drop tablewriter dependency

writer.go, writer_test.go
Seems bug was introduced in #218.
=> Fix #275 (panic after writer reset with multiple row groups)

buffer_pool.go
=> Fix fileBufferPool.PutBuffer file closing
