parquet_go18_test.go
schema.go
schema_test.go

fixes #2
When reconstructing the schema for nested structs we call function `fieldByIndex` to get the pointer to the underlying value of the field that we assign the values we read into.
This is the comment on fieldByIndex function
```go
// fieldByIndex is like reflect.Value.FieldByIndex but returns the zero-value of
// reflect.Value if one of the fields was a nil pointer instead of panicking.
```
In theory if we have a field with value `*Foo` a call to fieldByIndex should do the following when this field is not initialized yet (i.e is Nil)
- Create a zero value of `Foo` : `new(Foo)`
- Assign the zero value created to the field.
Before this change this is what fieldByIndex was doing
```go
if v.IsNil() {
v = reflect.Value{}
break
```
`reflect.Value{}` IS NOT A ZERO VALUE of anything , it …

fix: zero value of nested field pointer

---

merge.go
sorting_test.go

fixes #23
closes #24
Multiple layers of buffers were causing active rows memory to be overwritten  resulting in data corruption.
While merging rows, we buffer reads to speed up processing, however for cases where we need more data we were calling the underlying `RowGroup` multiple times resulting in  active buffers being overwritten.
Fixing `ReadRows` is a bit challenging. Without buffered reads it becomes a performance bottleneck.
Lucky for us there is an interface `RowWriterTo` which allows us to have control over the active buffers.
This commit implements `RowWriterTo` for the `MergeRowGroups` implementation.
In this case we ensure that values not yet written are not corrupted.

fix memory corruption in MergeRowGroups

---

writer.go

Fix a bug in recordPageStats that can cause the writer to corrupt the
min and max values of a byte-array column.
When processing the min and max values of a page to update the min and
max values in the column statistics, byte-array types would store values
backed by the page's values slice. This slice is reused when processing
the next page, and so data in the underlying array may be overwritten,
corrupting the stored min and max values, which can lead to wrong or
garbage values reported as the min or max.
To fix this, recordPageStats is modified to always copy the values into
a new slice owned exclusively by the statistics value, so that the
values remain correct after processing new pages.

Fix data corruption in column statistics

---

node.go
parquet_test.go
row.go
value.go

Fixes a few edge cases where conversions to and/or from `any` types would panic due to boxed reflect.Value types. I've added a unit test to run through the examples I've come across and plugged all the panics from those, but I'm fairly confident there will be other (even more edgier) cases lurking in there.

Fix panic reading/writing `any` types

---

file.go

Removes `format.PageHeader` caching, introduced in https://github.com/segmentio/parquet-go/pull/484. The impact of this optimization turned out to be less than expected after the page was reset before putting back into the pool (https://github.com/parquet-go/parquet-go/pull/11). Because of that, all the values referenced by pointers are lost, which was a significant part of the savings.
Even after that change, reusing page headers still could cause instability issues in certain edge cases. So, it's finally removed.
Fixes https://github.com/parquet-go/parquet-go/issues/70

Remove format.PageHeader caching

---

README.md

According to https://go.dev/ref/mod#go-mod-file
the line in go.mod denoting:
`go 1.20`
means Go 1.20+ is required to use with this module (since Go 1.21+ which is current it is no longer only advisory)
I think it makes sense to update this in documentation.

Fix minimum Go version in README documentation 

---

column.go
node.go
print.go
schema.go
schema_test.go
writer.go

Closes #20
Part of #44 
This commit adds `id` option on `parquet` tag which is in the form of `id={n}` where n is an `int32` denoting a field it.
The underlying infrastructure was already there. We just add api for users to define and access field id to the parquet schema.
Example
```go
type MySchema struct {
A string `parquet:"a,id=2"`
}
```
Will set column `a` field id to `2`.
Printing
-----
I wasn't so sure how to show the field id in the printed schema. I settled with showing the id next to the field name. I am open to any suggestions on how to improve field id printing.
The above schema is printed as
```
message {
required binary a = 2 (STRING);
}
```

add support for field id

---

writer.go

This prevents writing corrupted files due to integer overflows in cases where the uncompressed page size get's too large.
The PR helps to mitigate #79

Error when uncompressed page size exceeds the max int32 value

---

convert.go
convert_test.go

Slicing a missing page returns a new page with the same number of values. This causes issues when reading rows because columns end up with a different number of values.
This commit fixes that by setting the number of values in the page to the range of the slice.

Fix slicing a missing page

---

convert.go
convert_test.go

A missingColumnChunk can be created during schema conversion when a column does not exist in the target schema. The number of values for the chunk is considered to be equal to the number of rows in the row group, but the value returned by NumValues is currently 0.
Since the page of the chunk returns the number of rows in the group as number of values, it would be consistent for the chunk to do the same.

Fix NumValues for missingColumnChunk

---

column_index.go
column_index_test.go
go.mod
go.sum

Previously the base column index would return a pointer to the nullpages and nullcounts slices when generating a column index. However if the index was reset and reused these pointers would change the original value of the generated index.
This fixes that by copying the byte slices when generating the index instead of just using the slice pointers

Fix column index reuse

---

column_chunk.go
file.go
file_test.go

As a result of https://github.com/parquet-go/parquet-go/pull/84, we can now return a `nil` column or offset index when the `SkipPageIndex` option is set. Furthermore, if the page index is not skipped when opening a file, the return value for missing indices will be a zero-value struct instead of nil.
This commit reconciles this inconsistency by returning `ErrMissingColumnIndex` and `ErrMissingOffsetIndex` respectively when either index is missing.
Follow up to https://github.com/parquet-go/parquet-go/pull/85#discussion_r1400269216.

Return errors for missing page indices

---

column.go

As originally described in https://github.com/parquet-go/parquet-go/pull/96, column dictionaries are not properly sized befored decoding which leads to many small allocations in a loop.
This PR extracts the part of #96 which does buffer size estimation for dictionaries until we figure out a safe way to pool those buffers.
@asubiotto let me know what you think.

Estimate dictionary decode size

---

page.go
page_test.go

Currently if you reslice a boolean page it will not respect it's internal bit offset into the first byte. The impact is that if you slice a boolean page multiple times on values that are not byte aligned the page will return misaligned values when reading.

Bug: Respect current page offset in reslice

---

README.md

I happened to come across this somewhat odd typo.

Fix s/condution/conduct/

---

parquet_test.go
schema.go
schema_test.go

Fixes #112 
This allows specifying the delta tag on a `time.Time`.
I added a test to verify that it successfully creates a schema object, but have not verified that it actually uses the delta encoding.

Allow specifying delta on field of type time.Time

---

column.go
parquet_test.go
row.go
schema.go

As reported on #103, logical maps are currently read as the nested repeated structure used for their physical storage. This appears to be due to discarding the logical map in favor of a logical group. Attempting to work around this by providing a schema results in panics, as reported on #40, #57. This change adds a test for and fixes both of those cases. It also masks or fixes a resulting test panic; a deeper review is required for that.
- (*columnLoader).open: use mapType instead of groupType when the schema indicates a logical map
- reconstructFuncOfMap: handle map types and instantiation correctly when operating on an interface{} value
- makeNodeOf: questionable: don't panic for [][]uint8 case assuming it's actually []string
The makeNodeOf change is meant to address the panic in …

Read logical maps as go maps in Read[any]()

---

.github/workflows/test.yml
column_index.go
encoding/delta/byte_array.go
format/parquet.go
writer_test.go

The parquet-mr repository was renamed to parquet-java (see https://github.com/apache/parquet-java/pull/1357).
This PR updates our links to resources hosted in that repository.
Unblocks #140

CI: parquet-mr => parquet-java

---

hashprobe/aeshash/aeshash_amd64.go
hashprobe/aeshash/aeshash_amd64.s
hashprobe/aeshash/aeshash_test.go
hashprobe/aeshash/export_amd64_test.go
hashprobe/aeshash/export_test.go

This is used to seed the AES hash function. This commit reimplements aeskeysched locally to the package to avoid a dependency on runtime internals. In Go1.23 (yet to be released), runtime internals will require an explicit go:linkname directive to allow external packages to use them in order to lock down dependencies on runtime internals. runtime.aeskeysched is not currently exported so parquet-go builds are broken on Go1.23.
We could create a CL to add go:linkname to aeskeysched, but I don't think there's a good reason we can't remove the runtime dependency here.

hashprobe: remove dependency on runtime.aeskeysched

---

config.go
config_test.go

This PR solves the following issues: 
Fixes https://github.com/parquet-go/parquet-go/issues/107
A user reported to be unable to override the `MaxRowsPerRowGroup` field's default value even when explicitly passing the config as an option to the `GenericWriter` constructor.
`WriteConfig` implements the `WriterOption` interface so it should override the config when passed to `GenericWriter`, but the code was ignoring the `MaxRowsPerRowGroup` field from the `WriterOption`. Looking closer it was also ignoring the `DataPageStatistics` field. 
Adding coalesce functions for both fields did the job. Tests were added to verify the fix.

fix(config): allow MaxRowsPerRowGroup and DataPageStatistics fields to be set

---

bloom/xxhash/sum64uint_purego.go
encoding/delta/delta.go
parquet.go
sparse/gather.go

Poking around yesterday, I saw these repeated a few times, and now that we're upgraded to v1.21, the built-in mix/max funcs are available.

rm min/max funcs in favor of built-ins

---

dictionary.go
dictionary_test.go

There was a slice arithmetic bug in `newIndexedPage` that can cause a "slice bounds out of range" panic. This adds a very simple test to reproduce the issue and then includes the one-liner fix.

Fix panic in newIndexedPage

---

column_index.go
file.go

This allows a single `*parquet.File` to be safely used by multiple concurrent readers... I think. I suppose there may be other thread-safety issues lurking that I haven't yet found, so this begs the question: is this change appropriate?
It _seems_ like all of the state in a `File` is static/immutable after the file is opened with the exception of these indexes. So I'm hoping this change is in the right direction.
Resolves #167.

Use atomic pointer for column and offset indexes, so they can be lazily populated in a thread-safe way

---

column.go
node.go
schema_test.go

When loading a parquet file, the LIST logical type is never present, even if it's present in the actual schema in the file. This fixes that.

Fix bug where list fields don't report their logical type correctly

---

node.go

The parquet spec specifies that for backwards compatiblity the group can
be named `map` as well as `key_value`

support backwards compatible map schemas

---

.github/workflows/Dockerfile
bloom.go
bloom_be.go
bloom_le.go
column_buffer.go
dictionary.go
encoding/encoding_test.go
encoding/plain/plain.go
encoding/plain/plain_be.go
encoding/plain/plain_le.go
encoding/rle/rle.go
encoding/rle/rle_test.go
internal/bitpack/unpack_int32_be.go
internal/bitpack/unpack_int32_le.go
internal/bitpack/unpack_int32_purego.go
internal/bitpack/unpack_int64_purego.go
internal/unsafecast/unsafecast_test.go
value.go
value_be.go
value_le.go

Follow up to #164, this PR removes the `getOffset` function and moves all offset computation to build time constants.
I also moved most use of `cpu.IsBigEndian` to using separate files with build tags for consistency and to keep the main code logic as clean as possible. In some cases, this might also help with inlining since functions contain less code.
Let me know if you have any concerns about the change.

simplify big endian compat

---

config.go
file.go

This PR adds an option to skip reading magic bytes at the beginning of parquet files. The `PAR1` prefix is a useful indicator that the application is working with parquet files, but it is often unnecessary to read when we can trust the underlying data.
In scenarios like #188, this also likely removes one round trip to the storage layer, since we only need to read the footer to decode a parquet file schema and metadata.

file: add option to skip reading magic bytes

---

file.go

With this change, the `parquet.OpenFile` function will optimistically read the file footer using the configured read buffer size. Instead of performing two reads to the underlying file storage, in most cases the function can do a single read which contains both the footer size and data (when the footer data already fits in the read buffer).
In scenarios like #188, and when configured to skip optional sections, opening a parquet file now requires at most one round trip to the object store.

optimistically read file footer

---

buffer.go
file.go
multi_row_group.go
row_group.go

This PR changes the signature of `NewRowGroupRowReader` to take a read mode as argument, enabling programs to create a row group row reader in async mode when it's useful.
This is a breaking change, but I don't expect this migration to be hard to make, the compiler will pick up any misuse of the code, and usage of this API shouldn't be very common since programs would typically call `.Rows()` on row groups to get a reader over the rows.
Let me know if you have any concerns.

add read mode to NewRowGroupRowReader

---

column_buffer.go
column_buffer_test.go
reader_test.go
row.go

This PR fixes a bug that would trigger on an edge case where using a generic writer with type parameters and writing struct fields of slice type with both the `optional` and `list` tags set, for example:
```go
type record struct {
Values []float64 `parquet:",list,optional"`
}
```
Under those conditions, the definition levels were miscalculated, which resulted in all null values on those fields when reading the files back.

fix definition levels of typed optional list

---

column.go

This PR optimizes the `parquet.(*Column).Fields` method by caching the `[]Field` slice in the `Column` type instead of recomputing it on each call.

optimize parquet.(*Column).Fields

---

column_buffer.go
schema.go

In many cases, when constructing a schema, only subparts of it will be accessed. For example, if the schema is used as a wrapper for a pre-constructed `parquet.Node`. The inner state of the `parquet.Schema` type contains parts that are only needed under special circumstances.
This PR modifies the `parquet.Schema` implementation to lazily load parts of the schema depending on the application's usage of it. This avoids creating the column mapping or deconstructor/reconstructor functions.

Lazy load schema state

---

README.md

Updates outdated example of MergeRowGroups.
Closes #207.

docs: Fix MergeRowGroups example

---

convert.go

The interface as defined at:
https://github.com/parquet-go/parquet-go/blob/main/type.go#L210-L213 
The parameter `typ` is the conversion's **source** type, and the receiver defines the **target** type. 
This was accidentally reversed in this usage.

fix: Correct conversion order in convertToType function

---

column.go
column_index_be.go
column_index_le.go
file.go

In some cases it would be useful to read Column Chunks using a `ReaderAt` separate from the one coupled to the column chunk's row group's `File`. 
This PR does the following:
1. Adds methods to `fileColumnChunk` to support providing a `ReaderAt`
1. Exposes the `fileColumnChunk` -> `FileColumnChunk` type, so that we can preserve the existing `ColumnChunk` interface, while allowing callers to type assert to `FileColumnChunk` if they need to use the new methods that accept a `ReaderAt`

Expose `FileColumnChunk` with methods to provide a `ReaderAt`

---

bloom/xxhash/sum64uint_amd64.s
internal/bytealg/count_amd64.s

Reverts parquet-go/parquet-go#211

Revert "fix: change r15 usage so its not clobbered with go plugin buildmode"

---

type.go

Add constructors `TimestampAdjusted(unit TimeUnit, isAdjustedToUTC bool)` and `TimeAdjusted(unit TimeUnit, isAdjustedToUTC bool)` for compatibility with Apache Iceberg.
[Apache Iceberg specifically requires](https://iceberg.apache.org/spec/#parquet) that `time` fields have `adjustToUtc=false`, but this library is hard-coded to `true`. Similarly, Iceberg `timestamp` and `timestamptz` fields differ only by whether `adjustToUtc` is false (`timestamp`) or true (`timestamptz`).

feat: parameterize Time/Timestamp IsAdjustedToUTC

---

bloom/xxhash/sum64uint_amd64.s
encoding/rle/rle_amd64_test.go
internal/bytealg/count_amd64.s

Fixes #199 
The previous attempt in #211 caused file corruption due to an invalid reuse of register R8 in `bytealg.Count`, I reverted the change and I'm submitting this as a proper fix.

fix issue 199

---

buffer.go
convert.go
merge.go
multi_row_group.go
node.go
reader.go
row.go
writer.go

Comparing `Node`s for equality is not trivial. A function already exists, so let's export it.

feat: export NodesAreEqual

---

writer.go

Partial solution for #135 
By writing the bloom filter after the column chunks, they end up being near the page index in the common case where there is one row group per file.
It's possible that this is a good enough solution; for very large files that are split into multiple row groups, the bloom filters could grow so large that it's probably impractical to hold them all in memory. The optimization that consist in reading the footer, page index, and bloom filters at the same time might only apply to small to medium size files.
Let me know if you have more context to share @thorfour !

write bloom filters near page index

---

bloom.go
column.go
column_chunk.go
column_index.go
file.go
file_test.go
offset_index.go
reader.go
writer.go

This PR builds on #212 to expose more of the internal types. Having access to these types is useful because they expose methods that aren't part of the interfaces.

expose more file internals

---

file.go
file_test.go

We used to miss an API to access the column chunk statistics, this PR addresses it.
I added these to the `FileColumnChunk` type only instead of the `ColumnChunk` interface to avoid building dependencies, we can revisit in the future.

expose column chunk statistics

---

schema.go
schema_test.go

This PR extends https://github.com/parquet-go/parquet-go/pull/216 to add a second optional parameter to the `time` and `timestamp` tags to support explicitly setting the `isAdjustedToUTC` annotation.
Fixes https://github.com/parquet-go/parquet-go/issues/228

Add tag option to support isAdjustedToUTC

---

.github/workflows/thirdparty.yaml

Fixes: #232
This PR integrates critical Tempo unit tests into the `parquet-go` CI pipeline to ensure compatibility between `parquet-go` changes and Tempo.

ci(tempo): Ensure `parquet-go` compatibility with Tempo via CI tests

---

column.go
format/parquet.go
schema_test.go
type.go

This doesn't actually add useful support -- like the ability to encode/decode variant data to/from Go `any` values.
This is the most superficial of changes by merely adding the ability to _create_ a schema node that has a "variant" logical type (and only an unshredded variant). While superficial, It would still be useful since it would allow for experimenting locally with implementing the processing of variant data in a 3rd party library -- I'd have to handle it as a simple struct of two []byte fields, but at least I could produce a file with the right annotations in it, to test it out with other tooling that may support variants (like Apache Spark).
When looking at the changes in the upstream parquet-format repo, I noticed there were several other adjacent changes that have been made …

Rudimentary support for Variants when building a schema

---

buffer_test.go
column_buffer_test.go
dictionary_amd64.go
dictionary_test.go
parquet_test.go
reader_test.go
sorting_test.go
writer_test.go

I noticed that many of the test names that refer to issues all refer to issues that don't exist in this repo -- like `TestIssue272` in `writer_test.go` (current highest issue/PR number in this repo is ~250). Some reference issues as high as 500. I realized that these are issue numbers from the legacy (pre-fork) repo: https://github.com/segmentio/parquet-go/issues.
In the interest of clarity for future readers, I figured it might be nice to name them more clearly. I've renamed them all to include `Segmentio` in the name. So `TestIssueSegmentio272` refers to issue 272 in that other repo.
For test cases that referenced issues in _this_ repo (there were four of them), I didn't rename or touch them -- except 82, to remove an underscore that was inconsistent with other test case names.
What do …

Consistent test naming for legacy issues (issue numbers from segmentio repo)

---

writer.go
writer_test.go

I know this isn't perfectly backwards-compatible since it changes the return type of a method. But it's a very-newly-introduced method and this repo is still pre-v1.0, so this seemed okay.
This basically expands the interface of what you get back from `Writer.ColumnWriters()` so that you can actually flush pages from the buffer or have the writer auto-flush based on the page size (by using `WriteRows` instead of the lower level `WriteValues`).
This adds a new test that verifies equivalence between using `Writer.WriteRows`, `ColumnWriter.WriteRows`, and `ColumnWriter.WriteValues`.
This addresses the [latest observations/comment](https://github.com/parquet-go/parquet-go/issues/241#issuecomment-2682237551) on #241.
Closes #241.

Writer.ColumnWriters now returns concrete ColumnWriter type instead of ValueWriter

---

writer.go
writer_test.go

Without any columns, a columnar format cannot contain any rows, and thus no data. So it seems like it must be a programmer error (such as passing a struct with no exported fields).
Without these checks, we can later get into a index-out-of-range panics because some parts of the code assume at least one column is present.
Here's an example panic, that occurred when a writer was closed. This happened in an earlier form of the test added in the first commit of #242 (the test was later removed due to a decision to change/simplify how that functionality gets exposed).
```
--- FAIL: TestWriteRowsColumns (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 8 [running]: …
```

Don't allow a schema with zero columns

---

encoding.go

Currently it is possible to implement the `encoding.Encoding` interface to write parquet files but they cannot be read back since the list of considered encodings when reading is static and uses `encoding.LookupEncoding`. This PR makes it possible to read back parquet files that were written with a custom encoding.

ability to register extra encodings

---

.github/workflows/test.yml
.github/workflows/thirdparty.yaml
README.md

I was looking at submitting a feature, and CI was failing on my local fork because of out of date versions from setup-go.
While updating the CI pipelines, I figured I would bump some versions while I'm at it.
Lastly, fixed the TODO about enabling support for arm64

ci: update versions

---

buffer.go
buffer_test.go

Fixes: #134
This PR addresses the nil pointer panic that occurred when attempting to sort a Buffer or GenericBuffer configured with a SortingColumns option containing column names that do not exist in the buffer's schema.

fix(buffer): Improve Buffer resilience to invalid sort column names

---

file.go
file_test.go

This simple PR skips the dictionary decode if it's already been performed. This happens when ReadDictionary is called before ReadPage.
A potentially better, but harder, improvement would be to recognize in ReadDictionary that it can advance `f.rbuf` and do it correctly so the header is not double decoded.

Perf: Skip dictionary decode if we've already done it

---

page.go
page_internal_test.go

Putting this PR up for discussion. Tempo currently rarely panics with a stack trace like the following. We have found this quite difficult to reproduce. 
```
/Users/joe/dev/joe-elliott/tempo/vendor/github.com/parquet-go/parquet-go/page.go:129 +0xfd
created by github.com/parquet-go/parquet-go.AsyncPages in goroutine 610894
/Users/joe/dev/joe-elliott/tempo/vendor/github.com/parquet-go/parquet-go/page.go:269 +0x178
github.com/parquet-go/parquet-go.readPages({0x3fdf8f0, 0xc0bf919ae0}, 0xc10c1dc310, 0xc095e75880, 0x4007b18?, 0xc10c1dc3f0)
/Users/joe/dev/joe-elliott/tempo/vendor/github.com/parquet-go/parquet-go/file.go:801 +0x9f
github.com/parquet-go/parquet-go.(*FilePages).ReadPage(0xc0bf919ae0)
/Users/joe/dev/joe-elliott/tempo/vendor/github.com/parquet-go/parquet-go/file.go:916 +0x65 …
```

AsyncPages: Stop reading after err

---

schema_test.go
type.go
type_test.go

AFAICT this package has two implementations of the Parquet types int32 and int64. (This is true for other types; I'm just focusing on these two.)
- [`type intType format.IntType`](https://github.com/parquet-go/parquet-go/blob/401fed3de95633e24b110127f346a674f9c62a64/type.go#L1119); example: [`parquet.Int(32)`](https://github.com/parquet-go/parquet-go/blob/401fed3de95633e24b110127f346a674f9c62a64/type.go#L1074-L1080)
- [`type int32Type struct{}`](https://github.com/parquet-go/parquet-go/blob/2ff63c3c8bfd0af19d307c0600c04a4007a2d696/type.go#L349); example: `parquet.Leaf(parquet.Int32Type)`
The `LogicalType()` methods from these implementations differ - one returns nil, the other returns `INT(32, true)`. This causes `parquet.EqualNodes()` to signal the types are not equal. However, …

fix: missing int32 and int64 LogicalTypes

---

schema.go
schema_test.go

This change provides fine-grained control over the logical type used for `BYTE_ARRAY` physical types.

Add struct tags for altering the logical type of binary columns

---

config.go
sorting_test.go

`SortingWriter[T]` produce `min` / `max` index value even if `SkipPageBounds` option provided. `SkipPageBounds` added in #145.
(#294 was closed by mistake).

Fix #293 (apply SkipPageBounds to SortingWriter[T])

---

row.go
row_test.go

When reading a Parquet file containing a map field with insufficient definition level (indicating an empty map), the package panics if the target field is an interface. This occurs specifically in the `reconstructFuncOfMap` function when trying to create an empty map:
```
panic: reflect.MakeMapWithSize of non-map type
```
The panic happens because the code attempts to call reflect.MakeMap(value.Type()) directly on an interface value.
Modified the reconstructFuncOfMap function to handle interface values specially when creating empty maps for fields with insufficient definition levels:
```
if columns[0][0].definitionLevel < levels.definitionLevel {
valueType := value.Type()
if valueType.Kind() == reflect.Interface {
value.Set(reflect.ValueOf(map[string]any{}))
} else { …
```

fix: MakeMapWithSize panics with empty maps

---

convert.go
merge.go
merge_test.go
node.go
node_test.go
row_group_test.go
sorting.go
sorting_test.go
type.go
type_test.go

This change adds a new `MergeNodes` function which combines multiple parquet nodes in a greedy way to retain the most important properties of each node.
I ended up expanding the PR to add `EqualTypes` and tests for `EqualTypes` and `EqualNodes`, as well as fixing an inconsistency in `EqualNodes` (it was checking logical types of leaf nodes but node the logical types of group nodes).

add MergeNodes function to merge parquet nodes

---

row_test.go
schema.go
schema_test.go
type.go
value.go

Currently setting the uuid option on a string field will result in a panic. Setting it on a `[16]byte` field works but the generated parquet file doesn't not have the uuid logical type. This fixes both. Note that the physical type is always going to be `[16]byte` for uuid columns, but one can choose to create parquet files from inputs with string uuids.
Regarding the implementation, I added a `isUUID` flag to `be128Type` because it can be used for non uuid columns.
With this change we can see the uuid logical type in the schema of the generated parquet files.

Support uuid logical type for string and [16]byte types
